#include "families.hpp"
#include "hooks.hpp"
#include "brokers.hpp"
#include "world.hpp"
#include "combat.hpp"
#include "divine_policy.hpp"
#include <deque>
#include <numeric>

// Native, property-based reconstruction of the accepted server adapter. The
// original turn law/backstab/headshot behavior is not claimed to be recovered.
namespace csnz { namespace divine {
using namespace divine_policy;
struct Skill {double cost{},cycle{},scale{},radius{},damage{},speed{},life{},knockInterval{},knockXY{},knockZ{},invincibleDuration{},hitInterval=2,delay{},explosion{},touch{},kick{},slowTime{},slowSpeed{},aimDegree{},explosionDelay{},hookTime{},ammoSpeed{},traceLife{},traceWidth{},traceBrightness{},up{},forward{};Vec3 traceRGB;};
struct Values {int mode{};double charge{},maximum{},backDamageRate{},aDist{},aAngle{},aSlowTime{},aSlowSpeed{},aKnockXY{},aKnockZ{},rDamage{},rDelay{},rCycle{},rDist{},rAngle{},rKnockXY{},rKnockZ{},chargeStart{},chargeTime{},auraDelay{},auraInterval{},farRadius{},nearRadius{},farDamage{},nearDamage{},farSlowTime{},farSlowSpeed{},nearSlowTime{},nearSlowSpeed{},aniStart{},aniLoop{};std::array<double,4>aDamage{},aDelay{},aCycle{};
    Skill big,small,javelin;struct {double pitchMin{},pitchMax{},forward{},up{},alpha{};}cyclone;struct {int count{};std::vector<double> damage,interval;double duration{},slowTime{},slowSpeed{};}mark;
};
enum class Phase {Idle,PendingRight,Charging,Fired};
enum class Kind {Primary,Secondary,Storm,Gust,Javelin};
struct Pending {Kind kind;double at{};int stage{};};
struct Field {double old{},last{};bool integer{};};
struct State:Entity {Address weapon{},helper{},property{};Entity we;unsigned id{};Values v;int lastStage=-1,lastAnimation=-1,lastButtons{};double lastPrimary=-1000,nextAttack{},lastFrame{},chargeAt{},nextAura{},nextChargeAnim{};bool wasActive=true,bodyPending=false;std::optional<double> rightAt;Phase phase=Phase::Idle;std::vector<Pending> pending;std::map<unsigned,Field>writes;std::optional<std::pair<int,int>>body;int hand{};double handAt{};};
using StatePtr=std::shared_ptr<State>;
struct Basic {Address weapon{},owner{},pev{};unsigned id{};};
struct Slow {Entity entity;double until{},speed{};};
struct Protection {StatePtr state;double until{};};
struct Mark {StatePtr state;CombatTarget target;std::string key;double at{},until{},next{};int index=1;};
struct Projectile {unsigned id{};StatePtr state;Kind kind;double at{},last{},until{},nextKnock{},explosionAt{};Vec3 position,direction;Skill v;std::map<std::string,double>damageAt;bool blocked=false,exploded=false;std::optional<CombatTarget> lock;std::optional<Curve>curve;};
struct Trail {unsigned id{};StatePtr state;Skill v;double at{},last{};std::vector<Node>nodes,pending;Node head;bool finished=false,queueFinished=false;std::size_t cursor=1;unsigned formed{};std::deque<std::pair<Node,Node>>queue;};
std::map<Address,Address> helpers;std::map<Address,StatePtr> states;std::map<Address,Slow> statuses;std::map<Address,Protection>protections;std::map<std::string,Mark>marks;std::map<unsigned,Projectile>projectiles;std::map<unsigned,Trail>trails;
unsigned projectileId{};double clockValue=-1,globalStamp=-1;bool cleaned=false;
void(__cdecl* nativeSound)(Address,int,const char*,float,float,int,int){};
const Config& profile(){return profiles()["divinespear"];}
std::string stem(unsigned id){return id==4088?"divinespear":id==4128?"divinespearex":"divinespearexle";}
std::string identity(const Entity& e){return std::to_string(e.object)+":"+std::to_string(e.serial);}
std::optional<Basic> basic(Address w)noexcept{try{if(!w||ptr(w)!=at(profile()["knife"]["mp.dll"].u32())||read<unsigned>(w+0xe4)!=29)return {};const auto owner=ptr(w+0xd0);if(!owner)return {};const auto variant=read<int>(owner+0x2194);unsigned id=0;for(unsigned k:{4088u,4128u,4129u})if(selected(k)&&profile()["variants"][std::to_string(k)].integer()==variant)id=k;if(!id)return {};const auto pev=ptr(owner+8);if(!pev)return {};return Basic{w,owner,pev,id};}catch(...){return {};}}
bool helperValid(Address h,unsigned id)noexcept{try{return h&&ptr(h)==at(profile()["helpers"]["mp.dll"][std::to_string(id)].u32())&&read<int>(h+0xc)==profile()["variants"][std::to_string(id)].integer()&&read<int>(h+0x10)==(id==4088?0:id==4128?1:2);}catch(...){return false;}}
bool validState(const State& s)noexcept{try{const auto q=basic(s.weapon);return q&&q->owner==s.object&&q->pev==s.pev&&q->id==s.id&&helperValid(s.helper,s.id)&&ptr(s.helper+4)==s.property&&ptr(s.property)==at(profile()["properties"][std::to_string(s.id)].u32())&&valid(s)&&valid(s.we);}catch(...){return false;}}
bool sourceValid(const State& s){return alive(s);}
bool owned(const State& s){return sourceValid(s)&&validState(s);}
bool held(const State& s){return validState(s)&&alive(s)&&ptr(s.object+0x1024)==s.weapon;}
double prop(const State& s,unsigned off,unsigned index=0){if(ptr(s.helper+4)!=s.property||ptr(s.property)!=at(profile()["properties"][std::to_string(s.id)].u32()))throw std::runtime_error("Divine property identity");const auto q=s.property+off,first=ptr(q+0x1c),end=ptr(q+0x20);if(!first||end<first||end-first<4||end-first>256||(end-first)%4||index>=(end-first)/4)throw std::runtime_error("Divine property vector");const double v=read<float>(first+4*index);if(!std::isfinite(v))throw std::runtime_error("Divine nonfinite property");return v;}
Values values(const State& s){
    const auto p=[&](unsigned o,unsigned i=0){return prop(s,o,i);};Values v;const auto m=v.mode=csnz::mode();v.charge=p(0x118+0x38*m);v.maximum=p(0x1c0);v.backDamageRate=p(0xe0);
    for(unsigned i=0;i<4;i++){v.aDamage[i]=p(0x1f8+m*0x38,i);v.aDelay[i]=p(0x2a0,i);v.aCycle[i]=p(0x2d8,i);}v.aDist=p(0x3f0);v.aAngle=p(0x428);v.aSlowTime=p(0x310);v.aSlowSpeed=p(0x348);v.aKnockXY=p(0x380);v.aKnockZ=p(0x3b8);
    v.rDamage=p(0x460+m*0x38);v.rDelay=p(0x508);v.rCycle=p(0x540);v.rDist=p(0x578);v.rAngle=p(0x5b0);v.rKnockXY=p(0x5e8);v.rKnockZ=p(0x620);v.chargeStart=p(0x658);v.chargeTime=p(0x690);v.auraDelay=p(0x6c8);v.auraInterval=p(0x700);v.farRadius=p(0x738)*Meter;v.nearRadius=p(0x888)*Meter;v.farDamage=p(0x7e0+m*0x38);v.nearDamage=p(0x930+m*0x38);v.farSlowTime=p(0x770);v.farSlowSpeed=p(0x7a8);v.nearSlowTime=p(0x8c0);v.nearSlowSpeed=p(0x8f8);v.aniStart=p(0x9d8);v.aniLoop=p(0xa10);
    for(unsigned i=0;i<4;i++)if(v.aCycle[i]<.05||v.aCycle[i]>10||v.aDelay[i]<0||v.aDelay[i]>v.aCycle[i]||v.aDamage[i]<0||v.aDamage[i]>200000)throw std::runtime_error("Divine combo bounds");
    if(v.aDist<1||v.aDist>2048||v.rDist<1||v.rDist>2048||v.aAngle<=0||v.aAngle>360||v.rAngle<=0||v.rAngle>360||v.auraInterval<.05||v.chargeTime<.1||v.chargeTime>30||v.farRadius>2048||v.nearRadius>v.farRadius||v.nearRadius<1)throw std::runtime_error("Divine attack bounds");
    auto& b=v.big;b.cost=p(0xa48);b.cycle=p(0xa80);b.scale=p(0xab8);b.radius=p(0xaf0)*Meter;b.damage=p(0xb28+m*0x38);b.speed=p(0xbd0);b.life=p(0xc08);b.knockInterval=p(0xc40);b.knockXY=p(0xc78);b.knockZ=p(0xcb0);b.invincibleDuration=p(0xce8);
    auto& c=v.small;c.delay=p(0xd20);c.cycle=p(0xd58);c.scale=p(0xd90);c.radius=p(0xdc8)*Meter;c.damage=p(0xe00+m*0x38);c.speed=p(0xea8);c.life=p(0xee0);c.knockInterval=p(0xf18);c.knockXY=p(0xf50);c.knockZ=p(0xf88);c.invincibleDuration=p(0xfc0);
    v.cyclone={p(0xff8),p(0x1030),p(0x1068),p(0x10a0),p(0x10d8)};const auto markCount=p(0x1228);if(std::floor(markCount)!=markCount||markCount<1||markCount>32)throw std::runtime_error("Divine mark count");v.mark.count=int(markCount);
    for(int i=0;i<v.mark.count;i++){v.mark.damage.push_back(p(0x1110+m*0x38,i));v.mark.interval.push_back(p(0x11b8,i));}v.mark.duration=p(0x11f0);v.mark.slowTime=p(0x1260);v.mark.slowSpeed=p(0x1298);
    auto& j=v.javelin;j.cost=p(0x12d0);j.damage=p(0x1308+m*0x38);j.explosion=p(0x13b0+m*0x38);j.touch=p(0x1500+m*0x38);j.kick=p(0x15a8+m*0x38);j.slowTime=p(0x16c0);j.slowSpeed=p(0x16f8);j.invincibleDuration=p(0x1730);j.cycle=p(0x1768);j.delay=p(0x17a0);j.speed=p(0x17d8);j.life=p(0x1810);j.aimDegree=p(0x1848);j.explosionDelay=p(0x1880);j.hookTime=p(0x18b8+m*0x38);j.ammoSpeed=p(0x1960);j.traceLife=p(0x1c70);j.traceWidth=p(0x1ca8);j.traceRGB={float(p(0x1ce0)),float(p(0x1d18)),float(p(0x1d50))};j.traceBrightness=p(0x1d88);j.radius=p(0x1998)*Meter;j.up=p(0x1dc0);j.forward=p(0x1df8);
    for(const auto* x:{&b,&c})if(x->radius<=0||x->radius>2048||x->damage<0||x->damage>200000||x->speed<0||x->speed>4000||x->life<=0||x->life>30||x->knockInterval<.05||x->invincibleDuration<0||x->invincibleDuration>10||x->scale<=0||x->scale>30)throw std::runtime_error("Divine cyclone bounds");
    for(auto x:v.mark.damage)if(x<0||x>200000)throw std::runtime_error("Divine mark damage");for(auto x:v.mark.interval)if(x<.01||x>5)throw std::runtime_error("Divine mark interval");if(std::abs(std::accumulate(v.mark.interval.begin(),v.mark.interval.end(),0.)-v.mark.duration)>.15)throw std::runtime_error("Divine mark schedule");
    if(j.cost<1||j.cost>v.maximum||b.cost<1||b.cost>v.maximum||j.speed<1||j.speed>10000||j.life<=0||j.life>20||j.radius<=0||j.radius>2048||j.aimDegree<0||j.aimDegree>90||j.invincibleDuration<0||j.invincibleDuration>10||j.traceLife<0||j.traceLife>10||j.traceWidth<=0||j.traceWidth>100)throw std::runtime_error("Divine javelin bounds");
    for(auto x:{double(j.traceRGB.x),double(j.traceRGB.y),double(j.traceRGB.z),j.traceBrightness})if(x<0||x>255)throw std::runtime_error("Divine trail color");return v;
}
void setField(State& s,unsigned off,double value,bool integer=false){const auto address=s.weapon+off;const double old=integer?read<int>(address):read<float>(address);auto [i,inserted]=s.writes.try_emplace(off,Field{old,old,integer});if(integer){write(address,int(value));i->second.last=read<int>(address);}else{write(address,float(value));i->second.last=read<float>(address);}}
void cooldown(State& s,double seconds,double idle){for(unsigned off:{0x134u,0x13cu,0x144u}){const auto v=off==0x144?idle:seconds;setField(s,off+4,v-read<float>(s.weapon+off));setField(s,off,v);}}
Address bodyPointer(const State& s){if(ptr(ptr(s.weapon+8)+0x238)!=s.we.edict)throw std::runtime_error("Divine body identity");return ptr(s.weapon+8)+0x124;}
void syncBody(State& s,bool sendIdle=false){const auto address=bodyPointer(s);const auto body=read<int>(address),energy=read<int>(s.weapon+0x160);if(body<0||body>7||energy<0||energy>s.v.maximum)throw std::runtime_error("Divine body/energy bounds");const auto bits=(energy>=s.v.big.cost?1:0)|(energy>=s.v.javelin.cost?2:0);if(!s.body)s.body={{body&3,body&3}};if((body&3)!=s.body->second)s.body->first=body&3;const auto desired=(body&~3)|bits;if(desired!=body){write(address,desired);s.body->second=bits;s.bodyPending=true;}if(sendIdle&&s.bodyPending&&read<int>(s.pev+0x248)==0&&s.phase==Phase::Idle){engine.animation(s.weapon,0,0);s.bodyPending=false;}}
void animation(State& s,int number,double duration){syncBody(s);engine.animation(s.weapon,number,0);s.bodyPending=false;s.lastAnimation=number;setField(s,0x148,duration-read<float>(s.weapon+0x144));setField(s,0x144,duration);}
void sound(const State& s,const std::string& name){nativeSound(s.edict,1,name.c_str(),1,.8f,0,100);}
StatePtr state(Address w){const auto q=basic(w);if(!q)return {};const auto i=helpers.find(w);if(i==helpers.end()||!helperValid(i->second,q->id))return {};const auto old=states.find(w);if(old!=states.end()&&validState(*old->second)&&old->second->helper==i->second)return old->second;
    auto s=std::make_shared<State>();static_cast<Entity&>(*s)=entity(q->owner);s->we=entity(w);s->weapon=w;s->helper=i->second;s->property=ptr(s->helper+4);s->id=q->id;s->nextAttack=now()+std::max({.1,double(read<float>(w+0x134)),double(read<float>(w+0x13c))});s->lastFrame=now();if(!validState(*s))return {};s->v=values(*s);states[w]=s;log("Divine weapon ready "+std::to_string(s->id));return s;
}
void restoreStatuses(){StatusBroker::releaseAll("divinespear");statuses.clear();}
void naturalCharge(State& s,double t){if(!owned(s))return;const auto q=charge(read<int>(s.weapon+0x160),read<float>(s.weapon+0x254),t,s.v.charge,int(s.v.maximum));if(q){setField(s,0x160,q->energy,true);setField(s,0x254,q->deadline);}}
void protect(const StatePtr& s,double t,double duration){if(duration<=0||!sourceValid(*s))return;const auto old=protections.find(s->object);const auto until=std::max(t+duration,old!=protections.end()&&old->second.state->serial==s->serial?old->second.until:0.);protections[s->object]={s,until};}
std::optional<CombatTarget> target(Address ed,const State& s){try{if(!ed||read<int>(ed))return {};const auto o=ptr(ed+0x80);if(!o||o==s.object)return {};const auto e=entity(o);if(read<float>(e.pev+0x190)==0||read<float>(e.pev+0x178)<=0)return {};return CombatTarget{e,center(e),read<unsigned>(e.pev+0x1c8)};}catch(...){return {};}}
std::vector<CombatTarget> sphere(const State& s,Vec3 origin,double radius){std::vector<CombatTarget>out;std::set<Address>seen;Address ed=0;const auto world=engine.byIndex(0);for(unsigned i=0;i<512;i++){ed=engine.findSphere(ed,&origin,float(radius));if(!ed||ed==world||!seen.insert(ed).second)break;auto e=target(ed,s);if(e)out.push_back(*e);}return out;}
void knock(const CombatTarget& e,Vec3 origin,double xy,double z){if(!(e.flags&0x28))return;const auto d=unit(Vec3{e.center.x-origin.x,e.center.y-origin.y,0},{1,0,0});putVec(e.e.pev+0x20,{float(d.x*xy),float(d.y*xy),float(z)});}
void slow(const CombatTarget& e,const State& s,double duration,double speed){if(!(e.flags&0x28)||!hostile(e.e,s)||duration<=0||speed<0)return;auto i=statuses.find(e.e.object);if(i==statuses.end()||!valid(i->second.entity))i=statuses.insert_or_assign(e.e.object,Slow{e.e,0,speed}).first;i->second.until=std::max(i->second.until,now()+duration);i->second.speed=std::min(i->second.speed,speed);}
void statusFrame(double t){for(auto i=statuses.begin();i!=statuses.end();){auto& x=i->second;if(!valid(x.entity)){i=statuses.erase(i);continue;}if(t>=x.until||read<float>(x.entity.pev+0x178)<=0){StatusBroker::release("divinespear",x.entity);i=statuses.erase(i);continue;}StatusBroker::set("divinespear",x.entity,0x240,x.speed);++i;}}
void melee(State& s,const Pending& pending){const auto a=combatAim(s);const auto& v=s.v;const bool primary=pending.kind==Kind::Primary;const auto dist=primary?v.aDist:v.rDist,angle=primary?v.aAngle:v.rAngle,amount=primary?v.aDamage[pending.stage]:v.rDamage;
    for(const auto& e:sphere(s,a.source,dist)){if((e.flags&8)&&!hostile(e.e,s))continue;if(length(closest(e.e,a.source)-a.source)>dist||!inArc(a.direction,e.center-a.source,angle)||!visible(s,a.source,e))continue;
        if(damage(e.e,s,amount).delta>0&&v.mode==1&&hostile(e.e,s)){if(!primary||pending.stage==3)knock(e,a.source,primary?v.aKnockXY:v.rKnockXY,primary?v.aKnockZ:v.rKnockZ);if(primary)slow(e,s,v.aSlowTime,v.aSlowSpeed);}}
}
void aura(State& s){const auto& v=s.v;const auto origin=vec(s.pev+8);for(const auto& e:sphere(s,origin,v.farRadius)){if(!hostile(e.e,s))continue;const auto distance=length(closest(e.e,origin)-origin);if(distance>v.farRadius||!visible(s,combatAim(s).source,e))continue;const bool close=distance<=v.nearRadius;if(damage(e.e,s,close?v.nearDamage:v.farDamage).delta>0&&v.mode==1)slow(e,s,close?v.nearSlowTime:v.farSlowTime,close?v.nearSlowSpeed:v.farSlowSpeed);}}
bool spend(State& s,double cost){if(std::floor(cost)!=cost||cost<1||cost>s.v.maximum)throw std::runtime_error("Divine energy cost");const auto before=read<int>(s.weapon+0x160);if(before<cost)return false;setField(s,0x160,before-cost,true);return true;}
void mark(const StatePtr& s,const CombatTarget& e,double t){if(!valid(e.e)||!hostile(e.e,*s)||read<float>(e.e.pev+0x178)<=0)return;const auto key=identity(*s)+":"+identity(e.e);if(marks.count(key))return;if(marks.size()>=128)throw std::runtime_error("Divine mark limit");marks.emplace(key,Mark{s,e,key,t,t+s->v.mark.duration,t+s->v.mark.interval[0],1});damage(e.e,*s,s->v.mark.damage[0]);if(s->v.mode==1&&valid(e.e))slow(e,*s,s->v.mark.slowTime,s->v.mark.slowSpeed);}
void marksFrame(double t){for(auto i=marks.begin();i!=marks.end();){auto& m=i->second;if(!sourceValid(*m.state)||!valid(m.target.e)||read<float>(m.target.e.pev+0x178)<=0||t>m.until){i=marks.erase(i);continue;}while(m.index<m.state->v.mark.count&&t+1e-5>=m.next){damage(m.target.e,*m.state,m.state->v.mark.damage[m.index]);m.next+=m.state->v.mark.interval[m.index++];if(!valid(m.target.e)||read<float>(m.target.e.pev+0x178)<=0)break;}++i;}}
Aim cycloneAim(const State& s){auto a=combatAim(s);const auto& c=s.v.cyclone;const double pitch=clamp(-std::asin(clamp(a.direction.z,-1,1))*180/Pi,c.pitchMin,c.pitchMax)*Pi/180,yaw=std::atan2(a.direction.y,a.direction.x);a.direction={float(std::cos(pitch)*std::cos(yaw)),float(std::cos(pitch)*std::sin(yaw)),float(-std::sin(pitch))};a.source=a.source+a.direction*c.forward+Vec3{0,0,float(c.up)};return a;}
Projectile& newProjectile(const StatePtr& s,Kind kind,double t,Aim a,const Skill& v){if(projectiles.size()>=32)throw std::runtime_error("Divine projectile limit");Projectile p;p.id=++projectileId;p.state=s;p.kind=kind;p.at=p.last=p.nextKnock=t;p.until=t+v.life;p.position=a.source;p.direction=a.direction;p.v=v;return projectiles.emplace(p.id,std::move(p)).first->second;}
void cancelCharge(State& s,double t){if(s.phase==Phase::Charging){animation(s,10,.24);cooldown(s,.25,.24);s.nextAttack=std::max(s.nextAttack,t+.25);}s.rightAt.reset();s.phase=Phase::Idle;}
void requestHand(State& s,int code,double t){s.hand=code;s.handAt=t;}
void startBig(const StatePtr& s,double t){if(!spend(*s,s->v.big.cost))return;cancelCharge(*s,t);s->nextAttack=t+s->v.big.cycle;cooldown(*s,s->v.big.cycle,.65);animation(*s,11,.65);sound(*s,"weapons/divinespear_end_shoot.wav");auto a=combatAim(*s);a.source=vec(s->pev+8);a.direction=unit(Vec3{a.direction.x,a.direction.y,0},{1,0,0});newProjectile(s,Kind::Storm,t,a,s->v.big);protect(s,t,s->v.big.invincibleDuration);requestHand(*s,2,t);}
void startSmall(const StatePtr& s,double t){protect(s,t,s->v.small.invincibleDuration);s->pending.push_back({Kind::Gust,t+s->v.small.delay});s->nextAttack=t+s->v.small.cycle;cooldown(*s,s->v.small.cycle,.65);animation(*s,9,.65);sound(*s,"weapons/divinespear_end_shoot.wav");s->phase=Phase::Fired;}
void startJavelin(const StatePtr& s,double t){if(!spend(*s,s->v.javelin.cost))return;cancelCharge(*s,t);s->pending.push_back({Kind::Javelin,t+s->v.javelin.delay});s->nextAttack=t+s->v.javelin.cycle;cooldown(*s,s->v.javelin.cycle,1);animation(*s,12,1);protect(s,t,s->v.javelin.invincibleDuration);requestHand(*s,3,t);sound(*s,"weapons/divinespear_throw.wav");}
std::optional<CombatTarget> seek(const State& s,Vec3 origin,Vec3 forward,double range,double angle){std::optional<CombatTarget>best;double bestDot=std::cos(angle*Pi/180),bestDistance=std::numeric_limits<double>::infinity();for(const auto& e:sphere(s,origin,range)){if(!valid(e.e)||!hostile(e.e,s))continue;const auto offset=e.center-origin;const auto distance=length(offset);if(!std::isfinite(distance)||distance<1e-5||distance>range)continue;const auto d=dot(offset*(1/distance),forward);if(d+1e-9<bestDot||(best&&std::abs(d-bestDot)<=1e-9&&distance>=bestDistance)||!visible(s,origin,e))continue;best=e;bestDot=d;bestDistance=distance;}return best;}
void spawnJavelin(const StatePtr& s,double t){auto a=combatAim(*s);const auto& v=s->v.javelin;a.source=a.source+a.direction*v.forward+Vec3{0,0,float(v.up)};auto& p=newProjectile(s,Kind::Javelin,t,a,v);if(s->v.mode==1)p.lock=seek(*s,a.source,a.direction,v.speed*v.life,v.aimDegree);}
const Config& visualSpec(const std::string& path){const auto& spec=profile()["visuals"][path];if(spec["frames"].integer()<2||spec["frames"].integer()>1024||spec["fps"].number()<=0||spec["fps"].number()>120)throw std::runtime_error("Divine visual contract");return spec;}
void explosion(Projectile& p,double t){const auto& s=p.state;const auto& v=p.v;for(const auto& e:sphere(*s,p.position,v.radius)){if((e.flags&8)&&!hostile(e.e,*s))continue;if(length(closest(e.e,p.position)-p.position)>v.radius||!visible(*s,p.position,e))continue;if(damage(e.e,*s,v.explosion).delta>0){mark(s,e,t);if(s->v.mode==1&&valid(e.e)&&hostile(e.e,*s)){knock(e,p.position,v.kick,std::max(0.,v.kick*.25));slow(e,*s,v.slowTime,v.slowSpeed);}}}sound(*s,"weapons/divinespear_exp.wav");p.exploded=true;p.explosionAt=t;const auto& spec=visualSpec("sprites/ef_"+stem(s->id)+"_explo.spr");p.until=t+spec["frames"].number()/spec["fps"].number();}
void queueTrail(const Projectile& p,Vec3 from,Vec3 to,double t,bool finish=false){if(p.v.traceLife<=0)return;auto i=trails.find(p.id);if(i==trails.end()){if(trails.size()>=32)throw std::runtime_error("Divine trail limit");Trail q;q.id=p.id;q.state=p.state;q.v=p.v;q.at=p.at;q.nodes.push_back({from,p.at,0});q.pending=q.nodes;i=trails.emplace(p.id,std::move(q)).first;}auto& q=i->second;const auto& last=q.nodes.back();const auto distance=length(to-last.position);Node head{to,t,last.distance+distance};if(distance>=12||(finish&&distance>1e-5)){if(q.nodes.size()>=768)throw std::runtime_error("Divine trail points");q.nodes.push_back(head);}q.head=head;q.finished=finish||p.exploded;q.last=t;}
void track(Projectile& p,double t){if(!p.lock){p.curve.reset();return;}auto& e=*p.lock;if(p.state->v.mode!=1||!valid(e.e)||!hostile(e.e,*p.state)||read<float>(e.e.pev+0x178)<=0){p.lock.reset();p.curve.reset();return;}e.center=center(e.e);if(!visible(*p.state,p.position,e)){p.lock.reset();p.curve.reset();return;}if(!p.curve||t-p.curve->planned>=.05||p.curve->distance>=p.curve->total-.001)p.curve=plan(p.position,p.direction,e.center,p.v.speed,t);}
void advanceProjectile(Projectile& p,double t){const auto end=std::min(t,p.until);if(end<=p.last)return;const auto steps=p.kind==Kind::Javelin?std::max(1,int(std::ceil((end-p.last)*120))):1;const auto dt=(end-p.last)/steps;auto stepAt=p.last;for(int i=0;i<steps;i++){stepAt+=dt;if(p.kind==Kind::Javelin)track(p,stepAt);const auto from=p.position;const auto next=p.kind==Kind::Javelin&&p.curve?advance(*p.curve,p.v.speed*dt,p.direction):p.position+p.direction*(p.v.speed*dt);Trace tr{};if(p.kind==Kind::Storm||p.blocked){tr.fraction=1;tr.end=p.position;}else tr=trace(p.position,next,p.state->edict,p.kind==Kind::Javelin?0:1);p.position=tr.end;if(p.kind==Kind::Javelin)queueTrail(p,from,p.position,stepAt);if(tr.fraction<.999||tr.startSolid){if(p.kind==Kind::Javelin){const auto e=target(tr.edict,*p.state);if(e&&(!(e->flags&8)||hostile(e->e,*p.state))&&damage(e->e,*p.state,p.v.damage).delta>0)mark(p.state,*e,stepAt);explosion(p,stepAt);queueTrail(p,from,p.position,stepAt,true);break;}p.blocked=true;}}p.last=end;}
void projectileFrame(double t){for(auto i=projectiles.begin();i!=projectiles.end();){auto& p=i->second;const auto& s=p.state;if(!sourceValid(*s)||t<p.at-1){i=projectiles.erase(i);continue;}if(p.exploded){if(t>=p.until)i=projectiles.erase(i);else ++i;continue;}advanceProjectile(p,t);if(p.exploded){++i;continue;}if(t>=p.until){if(p.kind==Kind::Javelin){explosion(p,t);queueTrail(p,p.position,p.position,p.last,true);++i;}else i=projectiles.erase(i);continue;}if(p.kind!=Kind::Javelin){const bool knockNow=t>=p.nextKnock;for(const auto& e:sphere(*s,p.position,p.v.radius)){if(!hostile(e.e,*s)||length(closest(e.e,p.position)-p.position)>p.v.radius||!visible(*s,p.position,e))continue;auto& deadline=p.damageAt[identity(e.e)];if(t>=deadline){deadline=t+p.v.hitInterval;if(damage(e.e,*s,p.v.damage).delta>0)mark(s,e,t);}if(knockNow&&s->v.mode==1&&valid(e.e))knock(e,p.position,p.v.knockXY,p.v.knockZ);}if(knockNow)p.nextKnock=t+p.v.knockInterval;}++i;}}
void trailFrame(Trail& q,double t){const auto seal=[&]{if(q.pending.size()<2)return;q.queue.emplace_back(q.pending.front(),q.pending.back());q.formed++;const auto last=q.pending.back();q.pending={last};};const auto append=[&](const Node& node){if(length(node.position-q.pending.back().position)<.0001)return;if(q.pending.size()>1&&!spanFits(q.pending,node))seal();q.pending.push_back(node);if(q.formed==0||node.at-q.pending.front().at>=.06)seal();};
    while(q.cursor<q.nodes.size())append(q.nodes[q.cursor++]);if(!q.queueFinished&&(q.finished||t-q.pending.front().at>=.06)){append(q.head);seal();}if(q.finished)q.queueFinished=true;
    while(!q.queue.empty()){const auto& span=q.queue.front();const auto life=q.v.traceLife-std::max(0.,t-span.second.at);if(life<=0){q.queue.pop_front();continue;}const auto result=World::trailSpan("sprites/ef_"+stem(q.state->id)+"_throw.spr",span.first.position,span.second.position,life,q.v.traceWidth,q.v.traceRGB,q.v.traceBrightness);if(result==TrailResult::Budget||result==TrailResult::Stopped)break;q.queue.pop_front();}
}
void show(const std::string& key,const std::string& path,Vec3 position,Vec3 forward,double scale,double alpha,double age,bool sprite){const auto& spec=visualSpec(path);const auto frame=std::max(0.,age)*spec["fps"].number(),frames=spec["frames"].number();double value;if(spec["sprite"].boolean())value=spec["loop"].boolean()?std::fmod(frame,frames):std::min(frames-1,frame);else{const auto span=frames-1;value=(spec["loop"].boolean()?std::fmod(frame,span):std::min(span,frame))*256/span;}VisualOptions o;o.scale=float(scale);o.alpha=float(alpha);o.frame=float(std::min(255.999,value));o.angles=studioAngles(forward);o.renderMode=sprite?5:alpha<255?2:0;World::set("divinespear",key,path,position,o);}
void visualFrame(double t){if(!World::ready())return;std::set<std::string>wanted;for(const auto& [id,p]:projectiles){if(!sourceValid(*p.state))continue;const auto base=stem(p.state->id);const bool javelin=p.kind==Kind::Javelin;const auto path=p.exploded?"sprites/ef_"+base+"_explo.spr":javelin?"models/ef_"+base+".mdl":"models/ef_"+base+"_cyclone.mdl";const auto key="p"+std::to_string(id);wanted.insert(key);show(key,path,p.position,javelin?p.direction:unit(Vec3{p.direction.x,p.direction.y,0},{1,0,0}),p.exploded||javelin?1:p.v.scale,p.exploded||javelin?255:p.state->v.cyclone.alpha,t-(p.exploded?p.explosionAt:p.at),p.exploded);}
    for(const auto& [key,m]:marks){if(!valid(m.target.e))continue;const auto k="m"+key;wanted.insert(k);show(k,"sprites/ef_"+stem(m.state->id)+"_mark.spr",center(m.target.e),{1,0,0},.35,255,t-m.at,true);}
    for(const auto& [w,s]:states){if(s->hand){const auto code=s->hand;s->hand=0;if(held(*s)&&t-s->handAt<=.5)World::event("divinespeareffect",s->edict,vec(s->pev+8),vec(s->pev+0x74),code,s->id==4088?0:s->id==4128?1:2);}if(held(*s)&&s->phase==Phase::Charging){const auto key="c"+std::to_string(w);wanted.insert(key);show(key,"models/ef_"+stem(s->id)+"_chrg.mdl",vec(s->pev+8)+Vec3{0,0,-12},{1,0,0},2.5,255,t-s->chargeAt,false);}}
    for(auto i=trails.begin();i!=trails.end();){auto& q=i->second;if(!sourceValid(*q.state)||t<q.at-1||t>q.last+q.v.traceLife){i=trails.erase(i);continue;}trailFrame(q,t);++i;}World::retain("divinespear",wanted);
}
void startPrimary(State& s,double t){const auto& v=s.v;const auto stage=divine_policy::stage(s.lastStage,s.lastPrimary,t,*std::max_element(v.aCycle.begin(),v.aCycle.end())+.5);s.lastStage=stage;s.lastPrimary=t;s.nextAttack=t+v.aCycle[stage];s.pending.push_back({Kind::Primary,t+v.aDelay[stage],stage});cooldown(s,v.aCycle[stage],stage<2?.84:1.04);animation(s,stage+1,stage<2?.84:1.04);sound(s,"weapons/divinespear_attack"+std::to_string(stage+1)+".wav");}
void startSlash(State& s,double t){s.nextAttack=t+s.v.rCycle;s.pending.push_back({Kind::Secondary,t+s.v.rDelay});cooldown(s,s.v.rCycle,1.34);animation(s,6,1.34);sound(s,"weapons/divinespear_attack4.wav");}
void frame(const StatePtr& s,double t,unsigned buttons){const auto& v=s->v;const bool both=(buttons&0x801)==0x801,right=(buttons&0x800)!=0,left=(buttons&1)!=0;
    if(!s->wasActive){s->wasActive=true;s->nextAttack=t+std::max({.1,double(read<float>(s->weapon+0x134)),double(read<float>(s->weapon+0x13c))});s->lastStage=-1;s->lastPrimary=-1000;}auto pending=std::move(s->pending);s->pending.clear();for(const auto& p:pending){if(t<p.at){s->pending.push_back(p);continue;}if(p.kind==Kind::Gust)newProjectile(s,Kind::Gust,t,cycloneAim(*s),v.small);else if(p.kind==Kind::Javelin)spawnJavelin(s,t);else melee(*s,p);}
    if(both){if((s->lastButtons&0x801)!=0x801&&t>=s->nextAttack)startBig(s,t);s->lastButtons=buttons;return;}if((buttons&0x2000)&&!(s->lastButtons&0x2000)&&t>=s->nextAttack)startJavelin(s,t);
    if(right){if(!s->rightAt&&t>=s->nextAttack){s->rightAt=t;s->phase=Phase::PendingRight;}if(s->rightAt){const auto duration=t-*s->rightAt;if(s->phase==Phase::PendingRight&&duration>=v.chargeStart){s->phase=Phase::Charging;s->chargeAt=t;requestHand(*s,2,t);s->nextAura=t+v.auraDelay;s->nextChargeAnim=t+v.aniStart;animation(*s,7,v.aniStart+.01);}if(s->phase==Phase::Charging){if(t>=s->nextChargeAnim){animation(*s,8,v.aniLoop+.01);s->nextChargeAnim=t+v.aniLoop;}if(t>=s->nextAura){aura(*s);s->nextAura=t+v.auraInterval;}cooldown(*s,.1,std::max(.1,s->nextChargeAnim-t));if(t-s->chargeAt>=v.chargeTime)startSmall(s,t);}}}
    else if(s->rightAt){if(s->phase==Phase::PendingRight&&t-*s->rightAt<v.chargeStart)startSlash(*s,t);else cancelCharge(*s,t);s->rightAt.reset();s->phase=Phase::Idle;}if(left&&!right&&t>=s->nextAttack)startPrimary(*s,t);s->lastButtons=buttons;s->lastFrame=t;
}
void forget(){helpers.clear();states.clear();marks.clear();projectiles.clear();protections.clear();trails.clear();statuses.clear();clockValue=globalStamp=-1;}
void cleanup(){World::clear("divinespear");protections.clear();trails.clear();restoreStatuses();for(const auto& [w,s]:states){if(!owned(*s))continue;bool restored=false;if(s->body){const auto p=bodyPointer(*s);const auto body=read<int>(p);if((body&3)==s->body->second){const auto desired=(body&~3)|s->body->first;if(desired!=body){write(p,desired);restored=true;}}}for(const auto& [off,f]:s->writes){const auto p=w+off;const double value=f.integer?read<int>(p):read<float>(p);if(value==f.last){if(f.integer)write(p,int(f.old));else write(p,float(f.old));}}if(held(*s)&&(restored||(s->lastAnimation>=0&&read<int>(s->pev+0x248)==s->lastAnimation)))engine.animation(w,0,0);}states.clear();marks.clear();projectiles.clear();cleaned=true;}
void tick(){const auto t=now();if(clockValue>=0&&t<clockValue-1){states.clear();projectiles.clear();marks.clear();protections.clear();trails.clear();restoreStatuses();}clockValue=t;if(globalStamp==t)return;globalStamp=t;projectileFrame(t);marksFrame(t);statusFrame(t);for(auto i=protections.begin();i!=protections.end();)if(t>=i->second.until||!sourceValid(*i->second.state))i=protections.erase(i);else ++i;
    for(auto i=states.begin();i!=states.end();){const auto& s=i->second;if(!owned(*s)){i=states.erase(i);continue;}naturalCharge(*s,t);if(!held(*s)){s->hand=0;s->wasActive=false;s->pending.clear();s->rightAt.reset();s->phase=Phase::Idle;s->lastButtons=0;}++i;}visualFrame(t);
}
struct InputScope {Address weapon{};unsigned effective{};bool sampled=false;};
thread_local std::vector<std::shared_ptr<InputScope>>inputScopes;
}
bool divineClean(){return divine::cleaned;}
void installDivine(){using namespace divine;
    nativeSound=native<decltype(nativeSound)>(at(0x14fe930));World::onMapReset([]{forget();});
    Hooks::attach(at(0x10a7970),"divinespear",[](Invocation& v){v.createState<Address>(active&&!stopping&&basic(v.registers->ecx)?v.registers->ecx:0);},[](Invocation& v){const auto w=v.state<Address>();if(!w||!active||stopping)return;const auto q=basic(w);if(q&&helperValid(v.registers->eax,q->id))helpers[w]=v.registers->eax;});
    Hooks::attach(at(0x10a71f0),"divinespear",[](Invocation& v){auto& scope=v.createState<std::shared_ptr<InputScope>>();if(!active||stopping||!basic(v.registers->ecx))return;scope=std::make_shared<InputScope>();scope->weapon=v.registers->ecx;inputScopes.push_back(scope);},[](Invocation& v){const auto scope=v.state<std::shared_ptr<InputScope>>();if(!scope)return;if(inputScopes.empty()||inputScopes.back()!=scope)throw std::runtime_error("Divine input scope mismatch");inputScopes.pop_back();if(!active||stopping){if(!cleaned)cleanup();return;}auto s=state(scope->weapon);if(s&&held(*s)){frame(s,now(),scope->sampled?scope->effective:0);syncBody(*s,true);}});
    Hooks::attach(at(0x10a70c0),"divinespear",[](Invocation& v){if(!active||stopping||v.returnAddress!=at(profile()["input_sample_return_rva"].u32())||inputScopes.empty())return;auto& scope=inputScopes.back();const auto q=basic(v.registers->ecx);if(q&&scope->weapon==q->weapon){scope->effective=read<unsigned>(q->pev+0x1a4);scope->sampled=true;}});
    Hooks::attach(at(0x13f8a80),"divinespear",[](Invocation&){if(!active||stopping){if(!cleaned)cleanup();return;}tick();});
    DamageBroker::add("divinespear",[](const DamageContext& c){if(!active||stopping)return false;const auto i=protections.find(c.victim);if(i==protections.end())return false;const auto t=now();if(t>=i->second.until||(clockValue>=0&&t<clockValue-1)||!sourceValid(*i->second.state)){protections.erase(i);return false;}return true;});
}
}
